pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                
                   checkout scm
                echo "Installing Java"
                sh 'sudo apt-get -y install unzip java-1.8.0-openjdk'
               
                    echo "Installing Maven"
                sh 'sudo apt-get -y install maven'
                sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                sh 'mvn test'
                  }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                script {
                sh './jenkins/scripts/deliver.sh'
                }
            }   
        }
    }
}
