pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                
                   checkout scm
                    def mvnHome = tool 'maven-3'
                sh 'mvn clean install'
                sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                sh 'mvn test'
                  }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                script {
                sh './jenkins/scripts/deliver.sh'
                }
            }   
        }
    }
}
