pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                
                   checkout scm
                echo "Installing Java"
                sh 'sudo apt-get install -y default-jdk'
               
                    echo "Installing Maven"
                sh 'sudo apt-get -y install maven'
                sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        
       
        stage('Deliver') {
            steps {
                script {
                sh './jenkins/scripts/deliver.sh'
                }
            }   
        }
    }
}
